<?php

namespace Hris\LeaveBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LeaveRelativeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeaveRelativeRepository extends EntityRepository
{
}
