<?php

namespace Hris\TrainingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * instanceFacilitatorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class instanceFacilitatorRepository extends EntityRepository
{
}
