<?php

namespace Hris\TrainingBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TraininginstanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TraininginstanceRepository extends EntityRepository
{
    public function getAllTrainingInstance($limit = null)
    {
        $qb = $this->createQueryBuilder('b')
            ->select('b')
            ->addOrderBy('b.startdate', 'DESC');

        if (false === is_null($limit))
            $qb->setMaxResults($limit);

        return $qb->getQuery()
            ->getResult();
    }

}
